# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  product: Listado
  version: 1
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Indicador Outcome 1
    output: web, pdf
    folderitems:
    - title: Descripción del indicador
      url: /P1.html
      output: web

    - title: Ficha Tecnica
      url: /p1_sample1.html
      output: web, pdf

    - title: Sample 2
      url: /p1_sample2.html
      output: web, pdf

    - title: Sample 3
      url: /p1_sample3.html
      output: web, pdf

  - title: Indicador Outcome 2
    output: web, pdf

    folderitems:
    - title: Descripción del indicador
      url: /p1_sample4.html
      output: web, pdf

    - title: ficha tecnica
      url: /p1_sample5.html
      output: web, pdf

    - title: Sample 6
      url: /p1_sample6.html
      output: web, pdf

    - title: Sample 7
      url: /p1_sample7.html
      output: web, pdf
	  
	  
  - title: Indicador Outcome 3
    output: web, pdf

    folderitems:
    - title: Descrpcion del indicador
      url: /p1_sample4.html
      output: web, pdf

    - title: Ficha tecnica
      url: /p1_sample5.html
      output: web, pdf

    - title: Sample 6
      url: /p1_sample6.html
      output: web, pdf

    - title: Sample 7
      url: /p1_sample7.html
      output: web, pdf

